DELETE FROM seas.tier;

INSERT INTO seas.tier (min_score, max_score, created_at, updated_at, name)
VALUES
    (0, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '선원'),
    (100, 199, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '포수장'),
    (200, 299, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '갑판장'),
    (300, 399, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '항해사'),
    (400, 499, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '일등항해사'),
    (500, 599, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '부선장'),
    (600, 2147483647, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '선장');